version: 2.1

jobs:
  build:
    working_directory: ~/circleci-python
    docker:
      - image: "circleci/python:3.6.4"
    steps:
      - checkout
      - run: 
          python main.py
          working_directory: ~/circleci-python
          command: |
            git clone --depth 1 https://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@github.com/nickg100/docs.git
      - deploy:
          name: Trigger docs deployment
          working_directory: ~/circleci-python/docs
          command: |
            git config credential.helper 'cache --timeout=120'
            git config user.email "nikhilgrwl09@gmail.com"
            git config user.name "nickg100"
            git commit --allow-empty -m "Trigger deployment"
            # Push quietly to prevent showing the token in log
            git push -q https://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@github.com/nickg100/docs.git master

  test:
    working_directory: ~/circleci-python
    docker:
      - image: "circleci/python:3.6.4"
    steps:
      - checkout
      - run: python main-test.py

workflows:
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build